# Generated by Django 4.0.4 on 2022-05-01 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_key_alter_blog_pub_date_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 1)),
        ),
    ]
